FROM ghcr.io/cirruslabs/flutter:stable AS builder

ENV FLUTTER_ROOT=/usr/local/flutter
RUN flutter config --no-analytics

WORKDIR /app

# Copie seulement les fichiers nécessaires pour les dépendances d'abord (optimisation cache)
COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get

# Copie le reste du code
COPY . .

# Expose le port utilisé par flutter web-server
EXPOSE 8080

# Commande pour lancer le serveur de développement
CMD ["flutter", "run", "-d", "web-server", "--web-port=8080", "--web-hostname=0.0.0.0"]